# Generated by Django 2.0.3 on 2018-03-17 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger_score', models.IntegerField()),
                ('defendant_score', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(default=1000)),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w. @+-]+$', 'Der Name enthält ein ungültiges Zeichen', 'invalid')])),
                ('pw_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenger', to='ranking.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='defendant', to='ranking.Player'),
        ),
    ]
