# Generated by Django 2.0.3 on 2018-03-17 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20180317_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='challenger_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='defendant_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.FloatField(default=1000),
        ),
    ]
